name = "pop-li-share"
main = "index.js"
compatibility_date = "2025-01-01"
workers_dev = true

routes = [
  { pattern = "cve.wiki/s/*",   zone_name = "cve.wiki" },
  { pattern = "cve.wiki/img/*", zone_name = "cve.wiki" }
]

[[kv_namespaces]]
binding = "SCORES"
id = "3611f119249d41c897663557e9fd836e"
